
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Oct 29 22:36:29 EDT 2012
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int MINUS = 5;
  public static final int INT = 9;
  public static final int EOL = 8;
  public static final int EOF = 0;
  public static final int PLUS = 4;
  public static final int DIV = 3;
  public static final int error = 1;
  public static final int RPAREN = 7;
  public static final int TIMES = 2;
  public static final int LPAREN = 6;
}

